### ISSUE TITLE
No file iNemoEngineGeoMagAPI.h

### ISSUE THREAD

**Issue by Kitsune2222** [STMicroelectronics/STMems_Android_Sensor_HAL_Input#1]
Need iNemoEngineGeoMagAPI.h file for SENSOR_GEOMAG_ENABLE. MagnSensor.cpp error.

**Comment by Kitsune2222** [comment]
Please, help fix this problem. Not work orientation, need iNemoEngineGeoMagAPI.h

**Comment by mariotesi** [comment]
The iNemoEngineGeoMag is a library released to customers under licence agreement (LUA)
