### ISSUE TITLE
Is STMems supported on Intrinsyc Open-Q 2500?

### ISSUE THREAD

**Issue by ofirc** [STMicroelectronics/STMems_Android_Sensor_HAL_Input#3]
Hi,
I have the STEVAL-MKI128V6 sensor module (which contains 4 ST sensors).
I have the following product:
https://www.lantronix.com/products/open-q-2500-development-kit/

Which has a Qualcomm SoC Snapdragon™ Wear 2500 (APQ8009W) and an ARM 32-bit CPU, and a custom BSP version (Android Oreo for Wearables 8.1.0).

What is the bare minimum for having sensor integration support?
Are there shell commands / sysfs files / device tree files that I should look into?

Thanks,
Ofir

**Comment by mariotesi** [comment]
Hi,

please consider this project is the Android Sensor HAL project for Linux Input device framework

Could you tell us what kind of driver and software platform you intend to use on your target board ? 
Bing a Qualcomm platform you maybe need the drivers for the Hexagon DSP (sensor Hub / context hub) or you wants to use the alternative Input/IIO driver that relies on the I2C/SPI bus of SoC directly ?

**Comment by ofirc** [comment]
Hi Mario,
Thanks for the reply.
I want to use the alternative Input/IIO driver or i2c directly, and the Android configuration is the Android 8.1.0 for Wearables (Oreo) which is an AOSP fork from CAF (Code Aurora Forum) with an old Linux kernel 3.18 and some Qualcomm patches rebased on top.

**Comment by mariotesi** [comment]
This is not the proper channel for such kinds of requests. Please contact our local sales and support representatives, please refer to:
     - https://community.st.com/s/onlinesupport#/ols/
     - https://community.st.com/s/
